apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: larbizyoisco/my-app:be31d05113c3b78285f82f18300efa6c3016189b
        ports:
        - containerPort: 80
